gamepad_controller_cpp_node:
  ros__parameters:
    throttle_axis_index: 5
    brake_axis_index: 2
    steering_axis_index: 0
    shiftup_button_index: 0
    shiftdown_button_index: 3
    throttle_inverse: true
    brake_inverse: true